########## THEORY QUESTIONS ##########

Question = 1 >>> What is Generative AI and what are its primary use cases across industries?

Ans = Generative Artificial Intelligence (Generative AI) is a type of AI that can create new and original content such as text, images, audio, video, code, and data by learning patterns from large amounts of existing data.

 Unlike traditional AI, which mainly analyzes or classifies data, Generative AI produces new content that is similar to human-created content.

Simple Definition (Exam-friendly)

Generative AI is an AI technology that generates new content by learning patterns from existing data.

Primary Use Cases of Generative AI Across Industries
1. Healthcare

Medical report generation

Clinical documentation

Drug discovery and molecule design

Medical image enhancement

 Example: AI generating patient lab reports or summarizing medical records.

2. Education

Automatic note generation

Personalized learning content

Question paper and quiz creation

Virtual tutors

 Example: AI explaining complex topics in simple language.

3. Marketing & Advertising

Content writing (blogs, ads, slogans)

Social media post generation

Personalized campaigns

Brand storytelling

 Example: AI creating promotional content for products.

4. Software & IT Industry

Code generation and debugging

Software documentation

Test case generation

Chatbots and virtual assistants

 Example: GitHub Copilot suggesting code automatically.

5. Media & Entertainment

Music composition

Video and animation generation

Script writing

Game content creation

 Example: AI-generated background music for videos.

6. Finance

Automated financial reports

Fraud detection support

Risk analysis summaries

Customer service chatbots

 Example: AI generating monthly financial summaries.

7. Manufacturing & Engineering

Product design optimization

Simulation data generation

Predictive maintenance reports

 Example: AI designing optimized machine parts.

8. Retail & E-commerce

Product descriptions

Personalized recommendations

Customer support automation

 Example: AI generating customized shopping suggestions.

Advantages of Generative AI

Saves time and cost

Improves productivity

Enables creativity

Works at large scale

Question = 2 >>> Explain the role of probabilistic modeling in generative models. How do these models differ from discriminative models?

Ans = Probabilistic modeling is the foundation of generative models. It allows the model to learn the probability distribution of data and generate new samples from it.

🔹 What does probabilistic modeling mean?

It means representing data using probability distributions instead of fixed rules.

🔹 How probabilistic modeling works in generative models

Learning data distribution
Generative models learn the joint probability distribution

𝑃
(
𝑋
,
𝑌
)
P(X,Y)

where:

𝑋
X = input data (text, image, audio)

𝑌
Y = labels (optional)

Capturing uncertainty
Real-world data is uncertain and noisy. Probabilistic models handle:

Missing data

Variability

Multiple possible outputs

Sampling new data
Once the probability distribution is learned, the model can sample from it to create new data points.

📌 Example:
A text-generation model predicts the probability of the next word given previous words and samples from that distribution.

🔹 Why probabilistic modeling is important

Enables data generation

Handles uncertainty

Allows multiple possible outputs

Makes models flexible and realistic

2. Difference Between Generative and Discriminative Models
Feature	Generative Models	Discriminative Models
Probability learned	Joint probability 
𝑃
(
𝑋
,
𝑌
)
P(X,Y)	Conditional probability 
𝑃
(
𝑌
∣
𝑋
)
P(Y∣X)
Main goal	Generate new data	Classify or predict labels
Can create data?	✅ Yes	❌ No
Handles missing data	Better	Limited
Output type	Samples, images, text	Labels or probabilities
Example models	GPT, GANs, VAEs, Naive Bayes	Logistic Regression, SVM, CNN classifier

🔹 Simple Example

Generative model: Learns how handwritten digits look and can generate new digits.

Discriminative model: Learns to identify which digit (0–9) an image represents.

3. Key Concept Summary

Generative models model how data is produced

Discriminative models separate or classify data

Probabilistic modeling enables sampling, uncertainty handling, and realism


Question = 3 >>> What is the difference between Autoencoders and Variational Autoencoders (VAEs) in the context of text generation?

Ans = 1. Autoencoders (AE)
🔹 What is an Autoencoder?

An Autoencoder is a neural network that compresses input text into a latent representation and then reconstructs the same text from it.

🔹 Architecture

Encoder: Converts text → latent vector

Decoder: Reconstructs text from latent vector

🔹 In text generation

Mainly used for text compression, denoising, and feature extraction

Not ideal for generating new text, because:

Latent space is not structured

Cannot easily sample new meaningful sentences

🔹 Limitations

Deterministic (same input → same output)

No probability distribution in latent space

Poor creativity in text generation

2. Variational Autoencoders (VAE)
🔹 What is a VAE?

A Variational Autoencoder is a probabilistic generative model that learns a distribution over the latent space, not just fixed vectors.

🔹 Architecture

Encoder: Outputs mean (μ) and variance (σ²)

Latent space: Sampled using probability distribution

Decoder: Generates text from sampled latent vector

🔹 In text generation

Can generate new and diverse sentences

Enables smooth interpolation between sentences

Handles uncertainty and variability in language

3. Key Differences (Table)

Feature                 	Autoencoder (AE)	                  Variational Autoencoder (VAE)

Latent space	            Fixed, deterministic	              Probabilistic, structured

Probability modeling	    ❌ No	                              ✅ Yes

Sampling new text       	❌ Difficult	                          ✅ Easy

Diversity in output     	Low	                                    High

Creativity	                Limited	                                Better

Used for	                Reconstruction	                        Generation + reconstruction


Question = 4 >>> Describe the working of attention mechanisms in Neural Machine
Translation (NMT). Why are they critical?

Ans = Neural Machine Translation (NMT) uses neural networks to translate text from a source language to a target language.

📌 Example:
English → Hindi

“I am learning AI” → “मैं AI सीख रहा हूँ”

2. What is an Attention Mechanism?

The attention mechanism allows the model to focus on relevant words in the source sentence while generating each word in the target sentence.

👉 Instead of relying on a single fixed representation, attention dynamically selects important parts of the input.

3. Working of Attention Mechanism (Step-by-Step)
🔹 Step 1: Encoding the Source Sentence

The encoder (RNN/LSTM/GRU) converts each source word into a hidden state.

This produces a sequence of hidden states:

ℎ
1
,
ℎ
2
,
ℎ
3
,
.
.
.
,
ℎ
𝑛
h
1
	​

,h
2
	​

,h
3
	​

,...,h
n
	​

🔹 Step 2: Decoding with Attention

At each decoding step, the decoder:

Generates one target word at a time

Uses attention to decide which source words are most relevant

🔹 Step 3: Attention Score Calculation

The decoder computes alignment scores between:

Current decoder state

Each encoder hidden state

These scores measure relevance.

🔹 Step 4: Attention Weights (Softmax)

The scores are normalized using softmax to produce attention weights:

𝛼
1
,
𝛼
2
,
.
.
.
,
𝛼
𝑛
α
1
	​

,α
2
	​

,...,α
n
	​


Each weight shows how much importance a source word has.

🔹 Step 5: Context Vector Creation

A context vector is computed as a weighted sum of encoder states:

𝑐
=
∑
𝛼
𝑖
ℎ
𝑖
c=∑α
i
	​

h
i
	​

🔹 Step 6: Target Word Generation

The decoder combines:

Context vector

Decoder hidden state

to predict the next target word.

4. Why Attention is Critical in NMT
✅ Solves Long Sentence Problem

Traditional encoder–decoder models compress entire sentences into one vector.

Attention avoids information loss.

✅ Improves Translation Quality

Correct word alignment between languages.

Better handling of word order differences.

✅ Enables Interpretability

Attention weights show which source words influenced each translation step.

✅ Foundation for Transformers

Self-attention completely replaces RNNs in modern models like Transformer, BERT, GPT.

5. Simple Example

English: “The cat sat on the mat”
Hindi: “बिल्ली चटाई पर बैठी”

When generating “बिल्ली”, attention focuses on “cat”
When generating “चटाई”, attention focuses on “mat”


Question = 5 >>>  What ethical considerations must be addressed when using generative AI for creative content such as poetry or storytelling?


Ans = Ethical Considerations in Using Generative AI for Creative Content

(Poetry, Storytelling, Art, etc.)**

1. Authorship and Ownership

Who owns AI-generated poetry or stories?

Is the creator the user, the AI developer, or the model itself?

📌 Concern: Lack of clear copyright laws for AI-generated content.

2. Originality and Plagiarism

AI may generate content similar to existing works

Risk of unintentional plagiarism

📌 Concern: AI could mimic a known author’s style too closely.

3. Bias and Representation

AI learns from existing data, which may contain:

Cultural bias

Gender stereotypes

Social prejudice

📌 Concern: Stories may reinforce harmful stereotypes.

4. Transparency and Disclosure

Audiences should know whether content is AI-generated or human-written

📌 Concern: Misleading readers about the source of creative work.

5. Cultural Sensitivity

AI may misuse or misrepresent:

Cultural traditions

Folklore

Religious beliefs

📌 Concern: Offending communities or spreading misinformation.

6. Impact on Human Creativity

Over-reliance on AI may:

Reduce human creativity

Devalue human artists and writers

📌 Concern: AI replacing human creative jobs.

7. Misuse and Harmful Content

AI-generated stories could be used for:

Propaganda

Misinformation

Hate speech

📌 Concern: Ethical responsibility to prevent harmful outputs.

8. Data Privacy

Training data may include personal or sensitive information

📌 Concern: Violation of privacy and data protection laws.

9. Accountability

If AI generates offensive or harmful content:

Who is responsible?

📌 Concern: Lack of clear accountability frameworks.

10. Consent of Artists

Artists and writers may not have consented to their work being used in training data

📌 Concern: Ethical use of creative labor.


Question = 6 >>> Use the following small text dataset to train a simple Variational
Autoencoder (VAE) for text reconstruction:
["The sky is blue", "The sun is bright", "The grass is green",
"The night is dark", "The stars are shining"]
1. Preprocess the data (tokenize and pad the sequences).
2. Build a basic VAE model for text reconstruction.
3. Train the model and show how it reconstructs or generates similar sentences.
Include your code, explanation, and sample outputs.
(Include your Python code and output in the code box below.)

Ans = Dataset


In [4]:
sentences = [
    "The sky is blue",
    "The sun is bright",
    "The grass is green",
    "The night is dark",
    "The stars are shining"
]


1. Data Preprocessing (Tokenization & Padding)

In [5]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Dataset
sentences = [
    "The sky is blue",
    "The sun is bright",
    "The grass is green",
    "The night is dark",
    "The stars are shining"
]

# Tokenization
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

sequences = tokenizer.texts_to_sequences(sentences)

# Padding
max_len = max(len(seq) for seq in sequences)
padded_sequences = pad_sequences(sequences, maxlen=max_len, padding='post')

vocab_size = len(tokenizer.word_index) + 1

print("Vocabulary size:", vocab_size)
print("Padded sequences:\n", padded_sequences)


Vocabulary size: 14
Padded sequences:
 [[ 1  3  2  4]
 [ 1  5  2  6]
 [ 1  7  2  8]
 [ 1  9  2 10]
 [ 1 11 12 13]]


2. Build a Simple Variational Autoencoder (VAE)

In [10]:
import tensorflow as tf
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense, Lambda
from tensorflow.keras.models import Model
from tensorflow.keras import backend as K

embedding_dim = 8
latent_dim = 4

# Encoder
inputs = Input(shape=(max_len,))
x = Embedding(vocab_size, embedding_dim, mask_zero=True)(inputs)
x = LSTM(16)(x)

z_mean = Dense(latent_dim)(x)
z_log_var = Dense(latent_dim)(x)

# Sampling function
def sampling(args):
    z_mean, z_log_var = args
    epsilon = K.random_normal(shape=(K.shape(z_mean)[0], latent_dim))
    return z_mean + K.exp(0.5 * z_log_var) * epsilon

z = Lambda(sampling)([z_mean, z_log_var])

# Decoder
decoder_input = Dense(16, activation='relu')(z)
decoder_output = Dense(max_len * vocab_size, activation='softmax')(decoder_input)
from tensorflow.keras.layers import Reshape

decoder_output = Reshape((max_len, vocab_size))(decoder_output)


# VAE model
vae = Model(inputs, decoder_output)

# Loss
reconstruction_loss = tf.keras.losses.sparse_categorical_crossentropy(
    inputs, decoder_output
)
# Reconstruction loss
reconstruction_loss = tf.keras.losses.sparse_categorical_crossentropy(
    inputs, decoder_output
)


3. Train the Model
4. Text Reconstruction & Generation

Question = 7 >>> Use a pre-trained GPT model (like GPT-2 or GPT-3) to translate a short
English paragraph into French and German. Provide the original and translated text.


1. Introduction

A pre-trained GPT model (such as GPT-2 or GPT-3) is a generative language model trained on large amounts of multilingual text. Although GPT models are primarily designed for text generation, they can also perform machine translation through prompt-based learning.

2. How GPT Performs Translation

GPT models use a prompt that clearly instructs the model to translate text from one language to another.

The English paragraph is provided as input.

The prompt specifies the target language (French or German).

The model predicts the translated text based on learned language patterns.

This method does not require additional training.

3. Example
Original English Text

Artificial intelligence is transforming the world by improving healthcare, education, and communication.

French Translation

L’intelligence artificielle transforme le monde en améliorant les soins de santé, l’éducation et la communication.

German Translation

Künstliche Intelligenz verändert die Welt, indem sie das Gesundheitswesen, die Bildung und die Kommunikation verbessert.

4. Why Pre-trained GPT Works Well for Translation

Learns grammar and vocabulary from large multilingual datasets

Understands context and sentence structure

Produces fluent and natural translations

Works without task-specific fine-tuning

5. Limitations

GPT is not specialized only for translation

May produce less accurate results for technical or rare language pairs

Translation quality depends on prompt clarity

6. Conclusion

Pre-trained GPT models can effectively translate English text into French and German using prompt-based instructions, making them a flexible and powerful tool for multilingual text generation.

Question = 8 >>>  Implement a simple attention-based encoder-decoder model for
English-to-Spanish translation using Tensorflow or PyTorch.


1. Introduction

An attention-based encoder–decoder model is a neural network architecture used in Neural Machine Translation (NMT). It translates a sentence from a source language (English) to a target language (Spanish) by learning how words in the source sentence align with words in the target sentence.

2. Encoder

The encoder reads the English input sentence word by word and converts it into a sequence of hidden states using models like RNN, LSTM, or GRU.

Each word is first converted into a vector using an embedding layer.

The encoder produces a hidden representation for every input word.

These hidden states store semantic and contextual information about the sentence.

3. Attention Mechanism

The attention mechanism allows the model to focus on relevant words in the English sentence while generating each Spanish word.

Instead of using a single fixed context vector, attention computes weights for all encoder hidden states.

Higher weights are given to more relevant words.

A context vector is created as a weighted sum of encoder hidden states.

This helps the model handle long sentences, word order differences, and better alignment between English and Spanish words.

4. Decoder

The decoder generates the Spanish translation one word at a time.

It uses the context vector from attention and its own previous hidden state.

At each time step, it predicts the next Spanish word using a softmax layer.

The process continues until an end-of-sentence token is generated.

5. Training Process

The model is trained using parallel English–Spanish sentence pairs.

Teacher forcing is commonly used, where the correct previous word is given to the decoder during training.

The loss function (usually categorical cross-entropy) measures how close the predicted words are to the correct translation.

6. Advantages of Attention-Based Models

Improves translation accuracy

Handles long and complex sentences

Provides better word alignment

Forms the basis of Transformer models

7. Conclusion

An attention-based encoder–decoder model enhances English-to-Spanish translation by dynamically focusing on the most relevant parts of the input sentence, leading to more accurate and fluent translations compared to traditional encoder–decoder models.

Question = 9 >>> Use the following short poetry dataset to simulate poem generation with a
pre-trained GPT model:
["Roses are red, violets are blue,",
"Sugar is sweet, and so are you.",
"The moon glows bright in silent skies,",
"A bird sings where the soft wind sighs."]
Using this dataset as a reference for poetic structure and language, generate a new 2-4
line poem using a pre-trained GPT model (such as GPT-2). You may simulate
fine-tuning by prompting the model with similar poetic patterns.
Include your code, the prompt used, and the generated poem in your answer.

In [28]:
poetry_dataset = [
    "Roses are red, violets are blue,",
    "Sugar is sweet, and so are you.",
    "The moon glows bright in silent skies,",
    "A bird sings where the soft wind sighs."
]


Ans = 1. Introduction

A pre-trained GPT model (like GPT-2 or GPT-3) is a generative language model trained on large text corpora. It can generate creative text such as poetry by predicting the next word in a sequence based on learned patterns.

2. Using GPT for Poem Generation

Step 1: Reference Dataset
Provide a small set of poems as examples to guide the model’s style and structure.

Step 2: Prompting
Construct a prompt that instructs GPT to generate new poetic lines similar to the reference dataset.
Example prompt:

Write a 2-4 line poem similar to:
Roses are red, violets are blue,
Sugar is sweet, and so are you.


Step 3: Generation
The model uses its pre-trained knowledge of grammar, syntax, and word patterns to produce new lines that resemble the style and rhythm of the input examples.

Step 4: Sampling Parameters

Temperature controls creativity (higher → more diverse output).

Max length limits the number of generated tokens.

Top-k / top-p sampling can reduce repetition.

3. Advantages of Using GPT

Can produce original poems without explicit fine-tuning.

Maintains syntactic and semantic coherence.

Flexible for different poetic styles by changing prompts.

4. Example Output

Given the reference lines:

Roses are red, violets are blue,
Sugar is sweet, and so are you.


GPT might generate:

Stars twinkle softly above the trees,
A gentle breeze whispers through the leaves.
Night falls quietly, the world at rest,
Dreams awaken in every heart's chest.

5. Limitations

GPT may generate nonsensical or repetitive lines if the prompt is vague.

Quality depends on prompt clarity and sampling settings.

Not guaranteed to strictly follow meter or rhyme schemes.


Question = 10 >>>  Imagine you are building a creative writing assistant for a publishing
company. The assistant should generate story plots and character descriptions using
Generative AI. Describe how you would design the system, including model selection,
training data, bias mitigation, and evaluation methods. Explain the real-world challenges
you might face.


Ans = 1. System Overview

A creative writing assistant helps authors by generating:

Story plots

Character descriptions

Dialogue suggestions

It leverages Generative AI models, particularly large language models (LLMs), to produce coherent and imaginative content.

2. Model Selection

Pre-trained LLMs such as GPT-3, GPT-4, or open-source models like GPT-J / LLaMA are ideal because:

They understand grammar, context, and storytelling patterns.

They can generate diverse and creative outputs without extensive task-specific training.

For more controlled outputs, consider fine-tuning a pre-trained model on domain-specific creative writing datasets.

3. Training Data

Use high-quality storytelling datasets, including:

Published novels, short stories, and scripts (licensed or public domain)

Character and plot descriptions

Dialogue datasets

Preprocess the data:

Tokenization

Text cleaning

Maintaining style and formatting of stories

Optionally, create prompt–completion pairs for supervised fine-tuning.

4. Bias Mitigation

Generative models may replicate biases from training data. Mitigation strategies include:

Data curation: Remove or balance biased content (gender, ethnicity, religion, etc.)

Prompt engineering: Guide the model to produce inclusive and neutral content

Post-processing filters: Detect and remove offensive or inappropriate outputs

Regular audits: Check model outputs for bias or stereotypes

5. Evaluation Methods

Evaluate the system on multiple dimensions:

a. Creativity and Coherence

Human evaluators rate plots and character descriptions for originality, engagement, and logical consistency.

b. Fluency and Grammar

Use metrics like BLEU, ROUGE, or perplexity to measure language quality.

c. Diversity

Assess whether the model generates varied storylines and characters instead of repeating templates.

d. Ethical and Bias Evaluation

Ensure outputs are inclusive, culturally sensitive, and non-offensive.

6. Real-World Challenges

Bias and Offensive Content

AI can produce stereotypical or inappropriate characters if not monitored.

Intellectual Property Issues

Generated plots may inadvertently mimic existing copyrighted works.

Maintaining Coherence

Long story generation may lose plot consistency without advanced techniques like memory mechanisms or hierarchical generation.

Balancing Creativity vs. Control

Authors may need specific plot structures or themes, requiring controlled generation methods.

Evaluation Complexity

Creativity and storytelling quality are subjective, making automatic evaluation difficult.

7. System Architecture (High-Level)

Input Module

Accepts author prompts (e.g., “Generate a mystery story plot with a detective”).

Generative AI Module

Pre-trained GPT-like model, optionally fine-tuned

Generates plots, character sketches, and dialogues

Bias and Safety Filter

Removes offensive content, ensures inclusivity

Output Module

Presents multiple options

Allows author feedback to refine results
